#!/usr/bin/env bash
# This script transfers a file from a local client to the root directory of a remote server.

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$2"@"$3":~/
fi
