#!/usr/bin/env bash
# This script installs and configures nginx on a new ubuntu machine

file_path="/etc/nginx/sites-available/default"

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html

sed -i "s/^\s*location\s\/\s{.*$/       location \/redirect_me {/" "$file_path"

sed -i "/^\s*try_files\s$uri\s$uri\/\s=404;/a\\         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" "$file_path"

if pgrep nginx > /dev/null; then
        nginx -s reload;
else
        nginx;
fi
