#!/usr/bin/env bash
# This script configures haproxy to be managed via init script, direct traffice to two web servers and set the loadbalancing algorithm.

run_init="

# Enable HAProxy to start by init script
ENABLED=1
"

set_conf="

frontend 35278-lb-01
        mode http
        bind *:80
        default_backend web_servers

backend web_servers
        mode http
        balance roundrobin
        server 35278-web-01 100.26.138.201:80 check
        server 35278-web-02 54.209.126.230:80 check
"

apt-get update
apt-get install -y haproxy
echo -e "$run_init" >> /etc/default/haproxy
echo -e "$set_conf" >> /etc/haproxy/haproxy.cfg

if pgrep haproxy > /dev/null; then
        service haproxy restart;
else
        service haproxy start;
fi
