#!/usr/bin/env bash
# This bash script runs an nginx program - which by default binds to port 80 - if it exist or installs and runs the program if it does not exist. It also installs curl if it does not exist.

if  ! nginx -v &> /dev/null; then
        sudo apt-get update;
        sudo apt-get install -y nginx;
	sudo service nginx restart;
else 
        sudo rm /etc/nginx/sites-enabled/default;                            sudo ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default;
        sudo service nginx restart;
fi
