#!/usr/bin/env bash
# This bash script fixes nginx inability to bind on port 80 
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
