#!/usr/bin/env bash
# Print on a range of 1 t 20, fizz and buzz at multiple of 3 and#+ 5, and fizzbuzz at 15.

for i in {1..20}; do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done 
