#!/usr/bin/env bash
# This script reconfigures the localhost IP address and sets the hostname, facebook.com, to google DNS server IP address

sudo cp /etc/hosts hostsfile
sudo sed -i s/127.0.0.1/127.0.0.2/ hostsfile
sudo sed -i '$a\8.8.8.8	facebook.com' hostsfile
sudo cp hostsfile /etc/hosts

