#!/usr/bin/env bash
# This script reconfigures localhost and facebook.com IP addresses
cp /etc/hosts hosts.old
sed -i s/127.0.0.1/127.0.0.2/ hosts.old
sed -i "$ a\8.8.8.8	facebook.com" hosts.old
sudo cp hosts.old /etc/hosts
