#!/usr/bin/env bash
# Ensures non root user nginx has exclusive permission to run nginx

file_path="/etc/nginx/sites-available/default"
conf="/etc/nginx/nginx.conf"

# Allow traffic on port 8080
sudo ufw allow 8080

# Change the listening port in the sites-available default file
sed -i 's/80/8080/g' "$file_path"

# Change the user from www-data to nginx in the nginx configuration file
sed -i 's/#user www-data/user nginx/g' "$conf"

#Give read, write and execute to owner exclusively
chmod 744 "$conf"

# Reload nginx
sudo -u nginx service nginx start
