#!/usr/bin/env bash
# Ensures non root user nginx has exclusive permission to run nginx

file_path="/etc/nginx/sites-available/default"
conf="/etc/nginx/nginx.conf"

# Add nginx user if it doesn't exist
if ! id -u nginx > /dev/null 2>&1; then
	sudo useradd nginx;
fi

# Allow traffic on port 8080
sudo ufw allow 8080

# Change the listening port in the sites-available default file
sed -i 's/80/8080/g' "$file_path"

# Change the user from www-data to nginx in the nginx configuration file
sed -i 's/www-data/nginx/g' "$conf"

# Reload nginx
sudo service nginx reload
