#!/usr/bin/env bash
# Ensures non root user nginx has exclusive permission to run nginx
sed -i 's/80/8080/g' "/etc/nginx/sites-available/default"
sed -i 's/#user www-data/user nginx/g' "/etc/nginx/nginx.conf"
chmod 744 "/etc/nginx/nginx.conf"
pkill apache2
sudo -u nginx service nginx start
